### ISSUE TITLE
Strange Mobile Browser Problems

### ISSUE THREAD

**Issue by norsizu** [hihumanzone/Gemini-Pro-Chat-Interface#1]
I'm having a strange problem, everything works fine on desktop browsers, but on iPhone, whether it's safari or edge, it's asking me to enter the api key even though I've already entered the key. And in the desktop browser, even if I change the user-agent to put the browser into mobile mode, it works fine.

**Comment by hihumanzone** [comment]
> I'm having a strange problem, everything works fine on desktop browsers, but on iPhone, whether it's safari or edge, it's asking me to enter the api key even though I've already entered the key. And in the desktop browser, even if I change the user-agent to put the browser into mobile mode, it works fine.

Apologies for the delayed response; I was on vacation. Regarding the issue you're experiencing, I'm unsure about how it functions. I've made a minor adjustment to the code, but I can't guarantee it will fix the problem. Please let me know whether it resolves the issue or not. Also, could you try clearing the cookies and site data, and then re-enter the API key?

**Comment by norsizu** [comment]
Maybe it's my fault, I made the text box of the aip key hidden and then assigned it directly to the text box, at first it worked fine with desktop browsers maybe it was cached, so I switched to mobile browsers and it didn't work, and then the desktop browsers didn't support using it that way either. Have a nice vacation.

**Comment by hihumanzone** [comment]
> Maybe it's my fault, I made the text box of the aip key hidden and then assigned it directly to the text box, at first it worked fine with desktop browsers maybe it was cached, so I switched to mobile browsers and it didn't work, and then the desktop browsers didn't support using it that way either. Have a nice vacation.

![ezgif-1-b7c563e835](https://github.com/hihumanzone/Gemini-Pro-Chat-Interface/assets/101509991/3f80a881-8b9a-4274-9590-05be301b790a)

![ezgif-1-2d59b04130](https://github.com/hihumanzone/Gemini-Pro-Chat-Interface/assets/101509991/c516c280-ca62-457e-9160-d9e8c721677a)
